- name: Install Todo App on Managed nodes
  hosts: all
  remote_user: ec2-user
  vars_files:
    - vars_file
  
  tasks:
  - name: Install Python
    ansible.builtin.yum:
      name: python3
      state: latest
    become: yes

  - name: Install Git
    ansible.builtin.yum:
      name: git
      state: latest
    become: yes

  - name: install poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -

  - name: Create folder for Todo App
    ansible.builtin.file:
      path: /opt/todoapp
      state: directory
      owner: ec2-user
      mode: 0755
    become: yes

  - name: clone my git repo
    ansible.builtin.git:
      repo: https://github.com/puneets79/DevOps-Course-Starter.git
      dest: /opt/todoapp
      version: module-4

  
  
  - name: Install Poetry dependencies
    ansible.builtin.command:
      chdir: /opt/todoapp/
      cmd: /home/ec2-user/.local/bin/poetry install

  - name: Create .env file
    ansible.builtin.template:
      src: /home/ec2-user/ansible/.env.j2
      dest: /opt/todoapp/.env
      owner: ec2-user
      group: ec2-user
  
  - name: copy todoapp service file
    ansible.builtin.command:
      cmd: cp /opt/todoapp/todoapp.service /etc/systemd/system/todoapp.service
    become: yes
      
    
  - name: Start Todo App
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: true
      name: todoapp
    become: yes
  